/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
*/

public class Problem_002 {
    public static void main(String[] args) {
        int fn_2;
        int fn_1 = 1;
        int fn = 0;
        int sum = 0;
        while (fn <= 4000000) {
            if (fn % 2 == 0) {
                sum += fn;
            }
            fn_2 = fn_1;
            fn_1 = fn;
            fn = fn_2 + fn_1;
        }
        System.out.println(sum);
    }
}
